export const ALL_VEHICLE_REQUEST = "ALL_VEHICLE_REQUEST";
export const ALL_VEHICLE_SUCCESS = "ALL_VEHICLE_SUCCESS";
export const ALL_VEHICLE_FAIL = "ALL_VEHICLE_FAIL";

export const NEW_VEHICLE_REQUEST = "NEW_VEHICLE_REQUEST";
export const NEW_VEHICLE_SUCCESS = "NEW_VEHICLE_SUCCESS";
export const NEW_VEHICLE_RESET = "NEW_VEHICLE_RESET";
export const NEW_VEHICLE_FAIL = "NEW_VEHICLE_FAIL";

export const UPDATE_VEHICLE_REQUEST = "UPDATE_VEHICLE_REQUEST";
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";
export const UPDATE_VEHICLE_FAIL = "UPDATE_VEHICLE_FAIL";

export const DELETE_VEHICLE_REQUEST = "DELETE_VEHICLE_REQUEST";
export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";
export const DELETE_VEHICLE_FAIL = "DELETE_VEHICLE_FAIL";

export const NEW_TOLL_REQUEST = "NEW_TOLL_REQUEST";
export const NEW_TOLL_SUCCESS = "NEW_TOLL_SUCCESS";
export const NEW_TOLL_RESET = "NEW_TOLL_RESET";
export const NEW_TOLL_FAIL = "NEW_TOLL_FAIL";

export const ALL_TOLL_REQUEST = "ALL_TOLL_REQUEST";
export const ALL_TOLL_SUCCESS = "ALL_TOLL_SUCCESS";
export const ALL_TOLL_FAIL = "ALL_TOLL_FAIL";

export const DELETE_TOLL_REQUEST = "DELETE_TOLL_REQUEST";
export const DELETE_TOLL_SUCCESS = "DELETE_TOLL_SUCCESS";
export const DELETE_TOLL_RESET = "DELETE_TOLL_RESET";
export const DELETE_TOLL_FAIL = "DELETE_TOLL_FAIL";

export const TOLL_DETAILS_REQUEST = "TOLL_DETAILS_REQUEST";
export const TOLL_DETAILS_SUCCESS = "TOLL_DETAILS_SUCCESS";
export const TOLL_DETAILS_FAIL = "TOLL_DETAILS_FAIL";

export const UPDATE_TOLL_REQUEST = 'UPDATE_TOLL_REQUEST'
export const UPDATE_TOLL_SUCCESS = 'UPDATE_TOLL_SUCCESS'
export const UPDATE_TOLL_FAIL = 'UPDATE_TOLL_FAIL'

export const SHOW_MODAL_REQUEST = "SHOW_MODAL_REQUEST";
export const SHOW_MODAL_SUCCESS = "SHOW_MODAL_SUCCESS";
export const SHOW_MODAL_FAIL = "SHOW_MODAL_FAIL";





